version: '2'
services:

  vitimeo-downloader:
    image: registry.biggis.project.de/demo/vitimeo-downloader
    environment:
      START_YEAR: 2010
      END_YEAR: 2018
      FF_IMPORT_ENABLED: true
      EI_IMPORT_ENABLED: true
      MAP_IMPORT_ENABLED: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: true
    volumes:
      - kef-demo-data:/kef-demo-data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  kef-demo-data:
    driver: rancher-nfs
    external: true
